[Variables]

Language=English
Location=SPXX0050
Unit=m
ScrollMouseIncrement=0.1
Format=#I
Hidden=1
Hidden2=0
Player=Winamp

TextColor=60,207,230
ButtonColor=250,126,0




Bands=34
BarGap=5
BarWidth=17
BarHeight=225
MinBarHeight=1
PaletteColor1=204,0,40
FFTSize=2048
FFTBufferSize=16384
FFTAttack=0
FFTDecay=0
FreqMin=20
FreqMax=16744.03618
Sensitivity=62
AverageSize=10
Colors=Single
PaletteColor2=96,160,224
PaletteColor3=255,160,160
PaletteColor4=240,240,240
TransitionTime=12
hBlendingMultiplier=0
vBlendingMultiplier=0
OpacityLower=255
OpacityUpper=255
OpacityMultiplier=1
DecayEffect=0
DecayThreshold=55
DecaySustain=365
DecayDuration=635
DecayOpacityMin=0
DecayOpacityMax=255
bFXGhost=0
nFXGhostAttack=-1
nFXGhostDecay=390
ColorsExclude=
ModeKeyboard=0
FirstBandIndex=1
; !!! DO NOT CHANGE BELOW
SkinGroup=FountainOfColors
Config=Mond\Clone
SetCloneColorState=
Angle=180
Invert=1
Channel=
Port=
ID=
